DMC-TEST-A-00-00-00-00A-040A-D_EN-CA.pdf: DMC-TEST-A-00-00-00-00A-040A-D_EN-CA.XML highlight.xml
	s1kd-highlight -v highlight.xml $< | s1kd2pdf --out $@ -

clean:
	rm -f DMC-TEST-A-00-00-00-00A-040A-D_EN-CA.pdf
